version: "3"

services:
  lda:
    image: maven:3.5-jdk-8
    container_name: lda
    volumes:
    - ./:/usr/src/app/
    - ../../../.m2:/root/.m2 # TODO: cambiare in directory locale al progetto
    command: bash -c "mvn -f /usr/src/app/pom.xml clean install"
