version: "3"

services:
  angular:
    container_name: lda-web
    build:
      context: web/
      dockerfile: ../docker/angular.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./web/:/app
  lda-be:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: lda-be
    ports:
      - "8080:8080"
