version: "3"

services:
  lda:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: lda
    volumes:
    - ./:/usr/src/app/
    - ../../../.m2:/root/.m2 # TODO: cambiare in directory locale al progetto
    command: bash -c "mvn -f /usr/src/app/pom.xml clean install"
